# ----- Portfolio (free pass key) -----
portfolio.super-key.id=${PORTFOLIO_SUPER_KEY_ID:}
portfolio.super-key.otp=${PORTFOLIO_SUPER_KEY_OTP:}
#portfolio.super-key.role=ROLE_SUPER
portfolio.super-key.temp-passwd=${PORTFOLIO_SUPER_KEY_TEMP_PASSWD:}
