# ----- Project Name -----
spring.application.name=board_cafe_kiosk_2603
# ----- database Connection (MariaDB) -----
spring.datasource.mariadb.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.mariadb.url=jdbc:mariadb://localhost:3306/board_cafe_kiosk_2603
spring.datasource.mariadb.username=admin
spring.datasource.mariadb.password=0331
# ----- database Connection (PgVector) -----
spring.datasource.pgvector.url=jdbc:postgresql://localhost:5432/board_cafe_kiosk_2603
spring.datasource.pgvector.username=postgres
spring.datasource.pgvector.password=postgres
spring.datasource.pgvector.driver-class-name=org.postgresql.Driver
# ----- Log4j2 logging Levels -----
logging.level.org.springframework=info
logging.level.org.example.board_cafe_kiosk_2603=debug
# ----- Console log pattern -----
logging.level.org.mybatis=debug
logging.level.java.sql=debug
# logging pattern
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n
# ----- MyBatis Configuration -----
# ----- MyBatis: Location of Mapper XML files -----
# mybatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
# ----- Convert snake_case (DB) to camelCase (Java) -----
mybatis.configuration.map-underscore-to-camel-case=true
# ----- [Windows] File Upload Settings -----
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.location=c:\\upload
#spring.servlet.multipart.max-request-size=30MB
#spring.servlet.multipart.max-file-size=10MB
#my.upload.path=c:\\upload
# ----- [MacOS] File Upload Settings -----
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/Users/jy/upload
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB
my.upload.path=/Users/jy/upload
# ----- spring security logging config -----
logging.level.org.springframework.security=info
# error detail
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
# ----- spring Batch -----
# spring Batch Table Auto Create
spring.batch.jdbc.initialize-schema=always
# Prevent Spring Batch from executing jobs automatically on startup
spring.batch.job.enabled=false
# ----- toss payments -----
toss.payments.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
toss.payments.client-key=test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
toss.payments.confirm-url=https://api.tosspayments.com/v1/payments/confirm
# ----- Spring Boot Standard Mail Settings -----
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=wndus6110@naver.com
spring.mail.password=1EV12JZMHMGR
# ----- SMTP Additional Properties -----
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
myapp.custom.mail.sender.mailFrom=wndus6110@naver.com
myapp.custom.mail.sender.mailFromName=BOARD_WAVE_SYSTEM
# ----- Portfolio (free pass key) -----
spring.profiles.include=portfolio, key
# ----- PGVector -----
# postgres URL
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
# (?? ??)
#spring.datasource.driver-class-name=org.postgresql.Driver
# ??? ?? ?? ??
#spring.ai.vectorstore.pgvector.initialize-schema=false
# OpenAI
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
# durl_db
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
